 #*****************************************************************************
 #*                                                                           *
 #* Copyright FUJITSU LIMITED 2020                                            *
 #*                                                                           *
 #* Creation Date: 16-07-2020                                                 *
 #*                                                                           *
 #*****************************************************************************

FROM centos:7

ENV JAVA_HOME /usr/lib/jvm/java
ENV ANT_HOME /usr/share/ant

RUN yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel ant ant-contrib apache-ivy

ENTRYPOINT ["ant"]
